name = "b3-short"
main = "worker.js"
compatibility_date = "2024-09-01"
account_id = "b037edb5e4ac5dba49e8d3e03f5bde88"

# Тестовый адрес *.workers.dev — для проверки логики до активации зоны.
workers_dev = true

# KV-хранилище (база ссылок).
kv_namespaces = [ { binding = "LINKS", id = "55f46953c30742ae9ef89705df1a570b" } ]

# Маршрут добавим, когда зона b3.gg станет Active в Cloudflare:
# routes = [
#   { pattern = "b3.gg/*", zone_name = "b3.gg" },
#   { pattern = "www.b3.gg/*", zone_name = "b3.gg" }
# ]
